///////////////////////////////////////////////////////////
//  ApiService.cs
//  Implementation of the Class ApiService
//  Generated by Enterprise Architect
//  Created on:      29-9ÔÂ-2018 16:24:05
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AutoMapper;
using System.Data.Entity;
using System.Linq;
using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class ApiService : BaseService {

		/// 
		/// <param name="dbContext"></param>
		public ApiService(FormBuilderContent dbContext): base(dbContext){

		}

        /// 
        /// <param name="api"></param>
        /// <param name="userId"></param>
        public int AddApi(Api api, int userId)
        {
            var apiPo = Mapper.Map<Api, ApiPO>(api);
            apiPo.CREATED_BY = userId;
            _dbContext.Apis.Add(apiPo);
            _dbContext.SaveChanges();
            return (int)apiPo.API_ID;
        }

        /// 
        /// <param name="api"></param>
        /// <param name="userId"></param>
        public void SaveApi(Api api, int userId)
        {
            var apiPo = Mapper.Map<Api, ApiPO>(api);
            apiPo.CREATED_BY = userId;
            _dbContext.Apis.Add(apiPo);
            _dbContext.SaveChanges();
        }

		/// 
		/// <param name="apiId"></param>
		/// <param name="userId"></param>
		public void DelApi(int apiId, int userId){
            var api = _dbContext.Tables.Find(apiId);
            api.IS_DELETED = 1;
            api.MODIFIED_BY = userId;
            api.MODIFIED_TIME = DateTime.Now;
            _dbContext.SaveChanges();
        }

        ///         
        public List<Api> QueryApi()
        {
            var apis = _dbContext.Apis.ToList();
            var list = Mapper.Map<List<ApiPO>, List<Api>>(apis);
            return list;
        }

        /// 
        /// <param name="apiId"></param>
        public Api GetApi(int apiId)
        {
            var apiPo = _dbContext.Apis.Find(apiId);
            var api = Mapper.Map<ApiPO, Api>(apiPo);
            return api;
        }

	}//end ApiService

}//end namespace FD.Tiny.FormBuilder