///////////////////////////////////////////////////////////
//  BaseService.cs
//  Implementation of the Class BaseService
//  Generated by Enterprise Architect
//  Created on:      29-9ÔÂ-2018 15:36:34
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public class BaseService {

        protected FormBuilderContent _dbContext;

		/// 
		/// <param name="dbContext"></param>
		public BaseService(FormBuilderContent dbContext){
            this._dbContext = dbContext;
		}

	}//end BaseService

}//end namespace FD.Tiny.FormBuilder