///////////////////////////////////////////////////////////
//  DataService.cs
//  Implementation of the Class DataService
//  Generated by Enterprise Architect
//  Created on:      18-10ÔÂ-2018 17:18:39
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
using System.Linq;

namespace FD.Tiny.FormBuilder {
	public class DataService:BaseService<DataPO>
    {
        public DataService(IRepository<DataPO> repository) : base(repository)
        {

        }


        

    }//end DataService

}//end namespace FD.Tiny.FormBuilder