///////////////////////////////////////////////////////////
//  DatabaseService.cs
//  Implementation of the Class DatabaseService
//  Generated by Enterprise Architect
//  Created on:      29-9ÔÂ-2018 16:15:37
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AutoMapper;
using System.Data.Entity;
using System.Linq;
using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class DbTableService : BaseService<DbTablePO> {

		/// 
		/// <param name="dbContext"></param>
		public DbTableService(IRepository<DbTablePO> repository): base(repository)
        {

		}

		/// 
		/// <param name="table"></param>
		/// <param name="userId"></param>
		public int AddDbTable(DbTable table, int userId){

			var tablePo = Mapper.Map<DbTable, DbTablePO>(table);
            Repository.Add(tablePo, userId);
			return (int)tablePo.TABLE_ID;
		}



        /// 
        /// <param name="table"></param>
        /// <param name="userId"></param>
        public void SaveDbTable(DbTable table, int userId)
        {        
            var tablePo = Mapper.Map<DbTable, DbTablePO>(table);
            Repository.Update(tablePo, userId);
        }



        /// 
        /// <param name="tableId"></param>
        /// <param name="userId"></param>
        public void DelDbTable(int tableId, int userId)
        {
            var tablePo = Repository.FindSingle(r => r.TABLE_ID == tableId);
            Repository.SoftDelete(tablePo, userId);
        }

        public DbTable GetTable(int tableId)
        {
            var tablePo = Repository.FindSingle(r => r.TABLE_ID == tableId);
            return Mapper.Map<DbTablePO, DbTable>(tablePo);
        }

		/// <summary>
		///
		/// </summary>
		/// <param name="schemal"></param>
		public List<DbTable> QueryDbTable(string schemal){

			var tables = Repository.Find(r => r.SCHEMA_NAME.Equals(schemal)).ToList();
			var list = Mapper.Map<List<DbTablePO>, List<DbTable>>(tables);
			return list;
		}       

	}//end DatabaseService

}//end namespace FD.Tiny.FormBuilder