///////////////////////////////////////////////////////////
//  DictService.cs
//  Implementation of the Class DictService
//  Generated by Enterprise Architect
//  Created on:      21-11ÔÂ-2018 10:55:55
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class DictService : BaseService<DictionaryPO> {

        private static object locker = new object();


        /// 
        /// <param name="dbContext"></param>
        public DictService(IRepository<DictionaryPO> repository) : base(repository)
        {

        }



    }//end DictService

}//end namespace FD.Tiny.FormBuilder