///////////////////////////////////////////////////////////
//  DbColumn.cs
//  Implementation of the Class DbColumn
//  Generated by Enterprise Architect
//  Created on:      30-9月-2018 15:06:52
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 数据库列表述表
	/// </summary>
	public class DbColumn {

		/// <summary>
		/// 列Id
		/// </summary>
		public int column_id{
			get;  set;
		}

		/// <summary>
		/// 列名称
		/// </summary>
		public string column_name{
			get;  set;
		}

		/// <summary>
		/// 列中文名称
		/// </summary>
		public string column_name_chs{
			get;  set;
		}

		/// <summary>
		/// 长度
		/// </summary>
		public int length{
			get;  set;
		}

		/// <summary>
		/// 精度
		/// </summary>
		public int precision{
			get;  set;
		}

		/// <summary>
		/// 位数
		/// </summary>
		public int scale{
			get;  set;
		}

		public DataType data_type{
			get;
			set;
		}

		public int table_id{
			get;
			set;
		}

	}//end DbColumn

}//end namespace FD.Tiny.FormBuilder