///////////////////////////////////////////////////////////
//  DbData.cs
//  Implementation of the Class DbData
//  Generated by Enterprise Architect
//  Created on:      22-10ÔÂ-2018 10:39:11
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public class DbData {

		public string table_name{
			get;
			set;
		}

		public string column_name{
			get;
			set;
		}

		public dynamic column_value{
			get;
			set;
		}

	}//end DbData

}//end namespace FD.Tiny.FormBuilder