///////////////////////////////////////////////////////////
//  DbTable.cs
//  Implementation of the Class DbTable
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:44:32
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;




namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 数据表描述类
	/// </summary>
	public class DbTable {

		/// <summary>
		/// 表Id
		/// </summary>
		public int table_id{
			get;  set;
		}

		/// <summary>
		/// 表名称
		/// </summary>
		public string table_name{
			get;  set;
		}

		/// <summary>
		/// 表中文名称
		/// </summary>
		public string table_name_chs{
			get;  set;
		}

		/// <summary>
		/// 表用户名称
		/// </summary>
		public string schema_name{
			get;  set;
		}

		/// <summary>
		/// 列集合
		/// </summary>
		public IList<DbColumn> column_list{
			get;  set;
		}

	}//end DbTable

}//end namespace Database