///////////////////////////////////////////////////////////
//  BaiduMapConfig.cs
//  Implementation of the Class BaiduMap
//  Generated by Enterprise Architect
//  Created on:      20-9ÔÂ-2018 11:54:45
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class BaiduMap : Map {

	}//end BaiduMap

}//end namespace FD.Tiny.FormBuilder