///////////////////////////////////////////////////////////
//  MapConfig.cs
//  Implementation of the Class Map
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 11:54:45
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 地图类
	/// </summary>
	public abstract class Map {

		/// <summary>
		/// 地图类别
		/// </summary>
		public string map_type{
			get;  set;
		}

	}//end Map

}//end namespace FD.Tiny.FormBuilder