///////////////////////////////////////////////////////////
//  MapServer.cs
//  Implementation of the Class MapServer
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 11:54:44
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 地图服务
	/// </summary>
	public class MapServer {

		/// <summary>
		/// 地图数据源
		/// </summary>
		public ApiDataSource api_data_source{
			get;  set;
		}

		/// <summary>
		/// 地图类型
		/// </summary>
		public MapServerType map_server_type{
			get;  set;
		}

	}//end MapServer

}//end namespace FD.Tiny.FormBuilder