///////////////////////////////////////////////////////////
//  ConditionRelate.cs
//  Implementation of the Class ConditionRelate
//  Generated by Enterprise Architect
//  Created on:      15-1月-2019 11:37:24
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class ConditionRelate : Relate {

		/// <summary>
		/// 关联条件
		/// </summary>
		public Condition condition{
			get;
			set;
		}

	}//end ConditionRelate

}//end namespace FD.Tiny.FormBuilder