///////////////////////////////////////////////////////////
//  ConditionRelate.cs
//  Implementation of the Class ConditionRelate
//  Generated by Enterprise Architect
//  Created on:      27-3月-2019 18:45:03
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class ConditionRelate : Relate {

		/// <summary>
		/// 关联条件
		/// </summary>
		public string condition_expr{
			get;
						set;
		}

	}//end ConditionRelate

}//end namespace FD.Tiny.FormBuilder