///////////////////////////////////////////////////////////
//  RelateConfig.cs
//  Implementation of the Class RelateConfig
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:28:05
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 关联配置
	/// </summary>
	public class RelateConfig {

		/// <summary>
		/// 关联标签列表
		/// </summary>
		public List<Relate> relate_list{
			get;  set;
		}

	}//end RelateConfig

}//end namespace FD.Tiny.FormBuilder