///////////////////////////////////////////////////////////
//  Relate.cs
//  Implementation of the Class Relate
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 14:17:23
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 关联项
	/// </summary>
	public class Relate {

		/// <summary>
		/// 标签id
		/// </summary>
		public int label_id{
			get;  set;
		}

		/// <summary>
		/// 关联名称
		/// </summary>
		public dynamic relate_name{
			get;  set;
		}

		/// <summary>
		/// 关联操作
		/// </summary>
		public string operator_str{
			get;  set;
		}

		/// <summary>
		/// 关联标签
		/// </summary>
		public Label label{
			get;  set;
		}

	}//end Relate

}//end namespace FD.Tiny.FormBuilder