///////////////////////////////////////////////////////////
//  Relate.cs
//  Implementation of the Class Relate
//  Generated by Enterprise Architect
//  Created on:      15-1月-2019 11:37:22
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 关联项
	/// </summary>
	public class Relate {

		/// <summary>
		/// 关联标签名称
		/// </summary>
		public string relate_label_name{
			get;  set;
		}

		/// <summary>
		/// 关联类型
		/// </summary>
		public RelateType relate_type{
			get;
			set;
		}

	}//end Relate

}//end namespace FD.Tiny.FormBuilder