///////////////////////////////////////////////////////////
//  ControlConfig.cs
//  Implementation of the Class ControlConfig
//  Generated by Enterprise Architect
//  Created on:      23-4ÔÂ-2019 9:43:00
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// ¿Ø¼þÅäÖÃ
	/// </summary>
	public class ControlConfig {

		public List<Option> control_options{
			get;
									set;
		}

		public int control_sort{
			get;
						set;
		}

		public string control_type{
			get;
						set;
		}

		public string change_func{
			get;
			set;
		}

		public string group_name{
			get;
						set;
		}

		public string select_func{
			get;
			set;
		}

		public string click_func{
			get;
			set;
		}

		public BaseControl base_control{
			get;
			set;
		}

	}//end ControlConfig

}//end namespace FD.Tiny.FormBuilder