///////////////////////////////////////////////////////////
//  DatabaseConfig.cs
//  Implementation of the Class DatabaseConfig
//  Generated by Enterprise Architect
//  Created on:      16-1月-2019 17:23:33
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 数据库配置
	/// </summary>
	public class DatabaseConfig {

		/// <summary>
		/// 表名称
		/// </summary>
		public string table_name{
			get;  set;
		}

		/// <summary>
		/// 列名称
		/// </summary>
		public string column_name{
			get;  set;
		}

	}//end DatabaseConfig

}//end namespace FD.Tiny.FormBuilder