///////////////////////////////////////////////////////////
//  DbColumn.cs
//  Implementation of the Class DbColumn
//  Generated by Enterprise Architect
//  Created on:      14-6月-2018 10:46:46
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.DataBuilder.Data;
namespace FD.Tiny.DataBuilder.Data {
	public class DbColumn : DbGeneral {
	 
		/// <summary>
		/// 数据类型
		/// </summary>
		public string data_type{ get;  set;} 
		/// <summary>
		/// 长度
		/// </summary>
		public int length{ get;  set;} 
		/// <summary>
		/// 精度
		/// </summary>
		public int precision{ get;  set;} 
		/// <summary>
		/// 主键
		/// </summary>
		public bool is_primary{ get;  set;} 
		/// <summary>
		/// 是否可空
		/// </summary>
		public bool is_nullable{ get;  set;} 
		/// <summary>
		/// 默认值
		/// </summary>
		public string default_value{ get;  set;} 		 

		public DbColumn(){

		}

		public int scale{
			get;
			set;
		}	 

	}//end DbColumn

}//end namespace Data