///////////////////////////////////////////////////////////
//  DbGeneral.cs
//  Implementation of the Class DbGeneral
//  Generated by Enterprise Architect
//  Created on:      14-6月-2018 10:35:34
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.DataBuilder.Data {
	public class DbGeneral {

		/// <summary>
		/// 名称
		/// </summary>
		public string name{ get;  set;} 
		/// <summary>
		/// 代码
		/// </summary>
		public string code{ get;  set;} 
		/// <summary>
		/// 备注
		/// </summary>
		public string comment{ get;  set;} 

		public DbGeneral(){

		}

	}//end DbGeneral

}//end namespace Data