///////////////////////////////////////////////////////////
//  DbIndex.cs
//  Implementation of the Class DbIndex
//  Generated by Enterprise Architect
//  Created on:      14-6ÔÂ-2018 10:35:34
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.DataBuilder.Data;
namespace FD.Tiny.DataBuilder.Data {
	public class DbIndex : DbGeneral {

		private bool is_unique;
		private bool is_cluster;

		public DbIndex(){

		}

	}//end DbIndex

}//end namespace Data