///////////////////////////////////////////////////////////
//  DbKey.cs
//  Implementation of the Class DbKey
//  Generated by Enterprise Architect
//  Created on:      14-6ÔÂ-2018 10:35:34
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.DataBuilder.Data;
namespace FD.Tiny.DataBuilder.Data {
	public class DbKey : DbGeneral {

		private IList<Columns> columns;
		private string constraint_name;
		private bool is_primary;

		public DbKey(){

		}

	}//end DbKey

}//end namespace Data