///////////////////////////////////////////////////////////
//  DbReference.cs
//  Implementation of the Class DbReference
//  Generated by Enterprise Architect
//  Created on:      14-6ÔÂ-2018 10:35:34
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.DataBuilder.Data;
namespace FD.Tiny.DataBuilder.Data {
	public class DbReference : DbGeneral {

		private DbTable parent_table;
		private DbTable child_table;
		private RefJoin joins;
		private ReIntegrity integrity;
		private FD.Tiny.DataBuilder.Data.DbTable ParentTable;
		private FD.Tiny.DataBuilder.Data.DbTable ChildTable;
		private FD.Tiny.DataBuilder.Data.RefJoin Joins;

		public DbReference(){

		}

	}//end DbReference

}//end namespace Data