///////////////////////////////////////////////////////////
//  DbSequence.cs
//  Implementation of the Class DbSequence
//  Generated by Enterprise Architect
//  Created on:      14-6月-2018 10:39:41
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.DataBuilder.Data;
namespace FD.Tiny.DataBuilder.Data {
	public class DbSequence : DbGeneral {
		/// <summary>
		/// 起始值
		/// </summary>
		public int start_with{ get;  set;} 
		/// <summary>
		/// 步增
		/// </summary>
		public int increment_by{ get;  set;} 
		/// <summary>
		/// 最小值
		/// </summary>
		public int min_value{ get;  set;} 
		/// <summary>
		/// 最大值
		/// </summary>
		public int max_value{ get;  set;} 
		/// <summary>
		/// 缓存
		/// </summary>
		public int cache{ get;  set;} 
	 

		public DbSequence(string name){
            this.name = name;
            this.start_with = 1;
            this.increment_by = 1;
            this.min_value = 1;
            this.max_value = 99999999;
            this.cache = 20;

        }

	}//end DbSequence

}//end namespace Data