///////////////////////////////////////////////////////////
//  DbTable.cs
//  Implementation of the Class DbTable
//  Generated by Enterprise Architect
//  Created on:      14-6ÔÂ-2018 10:46:37
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.DataBuilder.Data;
namespace FD.Tiny.DataBuilder.Data {
	public class DbTable : DbGeneral {

        public DbTable() { }

        public DbTable(string name)
        {
            this.name = name;
        }


        public IList<DbColumn> columns{
			get;  set;
		}

	}//end DbTable

}//end namespace Data