///////////////////////////////////////////////////////////
//  RefJoin.cs
//  Implementation of the Class RefJoin
//  Generated by Enterprise Architect
//  Created on:      14-6ÔÂ-2018 10:35:34
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.DataBuilder.Data;
namespace FD.Tiny.DataBuilder.Data {
	public class RefJoin {

		private DbKey parent_key;
		private DbColumn parent_table_column;
		private DbColumn child_table_column;
		private FD.Tiny.DataBuilder.Data.DbKey ParentKey;
		public FD.Tiny.DataBuilder.Data.DbColumn ParentTableColumn;
		public FD.Tiny.DataBuilder.Data.DbColumn ChildTableColumn;

		public RefJoin(){

		}

	}//end RefJoin

}//end namespace Data