///////////////////////////////////////////////////////////
//  SqlParserUtil.cs
//  Implementation of the Class SqlParserUtil
//  Generated by Enterprise Architect
//  Created on:      17-11ÔÂ-2018 15:26:09
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.Common.Utility.SqlParse {
    public class SqlParserUtil
    {

        /// 
        /// <param name="sql"></param>
        public static string GetParsedSql(string sql)
        {
            sql = sql.Trim().Replace("s+", "    ");
            sql = "" + sql + " ENDOFSQL";
            return SingleSqlParserFactory.GenerateParser(sql).GetParsedSql();
        }

        /// 
        /// <param name="sql"></param>
        public static List<SqlSegment> GetParsedSqlSegmentList(string sql)
        {
            sql = sql.Trim().Replace("s+", "    ");
            sql = "" + sql + " ENDOFSQL";
            return SingleSqlParserFactory.GenerateParser(sql).ReturnSqlSegments();
        }

    }//end SqlParserUtil

}//end namespace SqlParse