///////////////////////////////////////////////////////////
//  ControlType.cs
//  Implementation of the Enumeration ControlType
//  Generated by Enterprise Architect
//  Created on:      22-4月-2019 15:50:46
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public enum ControlType : int {

		/// <summary>
		/// 输入框
		/// </summary>
		input_base,
		/// <summary>
		/// 下拉框
		/// </summary>
		select,
		/// <summary>
		/// 多选框
		/// </summary>
		checkbox,
		/// <summary>
		/// 单选框
		/// </summary>
		radio,
		/// <summary>
		/// 自动完成框
		/// </summary>
		input_autocomplete,
		/// <summary>
		/// 文本域
		/// </summary>
		input_textarea,
		/// <summary>
		/// 时间
		/// </summary>
		time,
		/// <summary>
		/// 日期
		/// </summary>
		date,
		/// <summary>
		/// 计数器框
		/// </summary>
		input_number,
		/// <summary>
		/// 开关
		/// </summary>
		@switch,
		/// <summary>
		/// 滑块
		/// </summary>
		slider,
		/// <summary>
		/// 评分
		/// </summary>
		rate

	}//end ControlType

}//end namespace FD.Tiny.FormBuilder