///////////////////////////////////////////////////////////
//  DataSourceType.cs
//  Implementation of the Enumeration DataSourceType
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:09:40
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 数据源类型
	/// </summary>
	public enum DataSourceType : int {

		/// <summary>
		/// 字典
		/// </summary>
		Dict,
		/// <summary>
		/// 自定义
		/// </summary>
		Custom,
		/// <summary>
		/// 接口
		/// </summary>
		DataApi

	}//end DataSourceType

}//end namespace FD.Tiny.FormBuilder