///////////////////////////////////////////////////////////
//  DataType.cs
//  Implementation of the Enumeration DataType
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:09:40
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 数据类型
	/// </summary>
	public enum DataType : int {

		/// <summary>
		/// 数字
		/// </summary>
		Number,
		/// <summary>
		/// 字符串
		/// </summary>
		String,
		/// <summary>
		/// 时间
		/// </summary>
		Date

	}//end DataType

}//end namespace FD.Tiny.FormBuilder