///////////////////////////////////////////////////////////
//  DirectionType.cs
//  Implementation of the Enumeration DirectionType
//  Generated by Enterprise Architect
//  Created on:      27-3月-2019 18:05:53
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public enum DirectionType : int {

		/// <summary>
		/// 正向
		/// </summary>
		forward,
		/// <summary>
		/// 反向
		/// </summary>
		reverse

	}//end DirectionType

}//end namespace FD.Tiny.FormBuilder