///////////////////////////////////////////////////////////
//  FormatNumberMode.cs
//  Implementation of the Enumeration FormatNumberMode
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:24:22
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 数字格式化模式
	/// </summary>
	public enum FormatNumberMode : int {

		/// <summary>
		/// 大写数字
		/// </summary>
		UpperNumber,
		/// <summary>
		/// 人民币数字
		/// </summary>
		RMBNumber,
		/// <summary>
		/// 数字
		/// </summary>
		Number

	}//end FormatNumberMode

}//end namespace FD.Tiny.FormBuilder