///////////////////////////////////////////////////////////
//  LabelType.cs
//  Implementation of the Enumeration LabelType
//  Generated by Enterprise Architect
//  Created on:      30-11ÔÂ-2018 15:41:09
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public enum LabelType : int {

		control,
		variable,
		condition

	}//end LabelType

}//end namespace FD.Tiny.FormBuilder