///////////////////////////////////////////////////////////
//  MapServerType.cs
//  Implementation of the Enumeration MapServerType
//  Generated by Enterprise Architect
//  Created on:      20-9ÔÂ-2018 11:55:00
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public enum MapServerType : int {

		/// <summary>
		/// Â¥ÅÌÍ¼²ã
		/// </summary>
		Construction,
		/// <summary>
		/// Â¥¶°Í¼²ã
		/// </summary>
		Building,
		/// <summary>
		/// Íø¸ñÍ¼²ã
		/// </summary>
		Case

	}//end MapServerType

}//end namespace FD.Tiny.FormBuilder