///////////////////////////////////////////////////////////
//  RelateType.cs
//  Implementation of the Enumeration RelateType
//  Generated by Enterprise Architect
//  Created on:      23-1月-2019 16:54:05
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public enum RelateType : int {

		/// <summary>
		/// 联动
		/// </summary>
		combine,
		/// <summary>
		/// 可见
		/// </summary>
		visibility,
		/// <summary>
		/// 逆地址解析
		/// </summary>
		address,
		/// <summary>
		/// 定位
		/// </summary>
		location

	}//end RelateType

}//end namespace FD.Tiny.FormBuilder