///////////////////////////////////////////////////////////
//  RelateType.cs
//  Implementation of the Enumeration RelateType
//  Generated by Enterprise Architect
//  Created on:      15-1月-2019 11:35:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public enum RelateType : int {

		/// <summary>
		/// 联动
		/// </summary>
		combine,
		/// <summary>
		/// 可见
		/// </summary>
		visibility

	}//end RelateType

}//end namespace FD.Tiny.FormBuilder