///////////////////////////////////////////////////////////
//  ValidatorType.cs
//  Implementation of the Enumeration ValidatorType
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:09:40
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 验证类型
	/// </summary>
	public enum ValidatorType : int {

		/// <summary>
		/// 输入框
		/// </summary>
		Input,
		/// <summary>
		/// 远程
		/// </summary>
		Remote,
		/// <summary>
		/// 正则
		/// </summary>
		Regex

	}//end ValidatorType

}//end namespace FD.Tiny.FormBuilder