///////////////////////////////////////////////////////////
//  ValueMethod.cs
//  Implementation of the Enumeration ValueMethod
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:09:40
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 取值方式
	/// </summary>
	public enum ValueMethod : int {

		/// <summary>
		/// 常量
		/// </summary>
		Const,
		/// <summary>
		/// 公式
		/// </summary>
		Formula,
		/// <summary>
		/// 数据源
		/// </summary>
		Source

	}//end ValueMethod

}//end namespace FD.Tiny.FormBuilder