///////////////////////////////////////////////////////////
//  VariableType.cs
//  Implementation of the Enumeration VariableType
//  Generated by Enterprise Architect
//  Created on:      23-10ÔÂ-2018 9:07:11
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public enum VariableType : int {

		Label,
		Condition

	}//end VariableType

}//end namespace FD.Tiny.FormBuilder