///////////////////////////////////////////////////////////
//  VirableType.cs
//  Implementation of the Enumeration VirableType
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:09:40
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 变量类型
	/// </summary>
	public enum VirableType : int {

		/// <summary>
		/// 文本变量
		/// </summary>
		Text,
		/// <summary>
		/// 条件变量
		/// </summary>
		Condition

	}//end VirableType

}//end namespace FD.Tiny.FormBuilder