///////////////////////////////////////////////////////////
//  Api.cs
//  Implementation of the Class Api
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 17:00:58
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 数据源接口
	/// </summary>
	public class Api {

		/// <summary>
		/// 接口id
		/// </summary>
		public int api_id{
			get;  set;
		}

		/// <summary>
		/// 接口名称
		/// </summary>
		public string api_name{
			get;  set;
		}

		/// <summary>
		/// 接口描述
		/// </summary>
		public string api_desc{
			get;  set;
		}

		/// <summary>
		/// 接口地址
		/// </summary>
		public string api_url{
			get;  set;
		}

		/// <summary>
		/// sql语句
		/// </summary>
		public string sql_content{
			get;  set;
		}

		/// <summary>
		/// 请求参数列表
		/// </summary>
		public IList<ApiParameter> request_parameter_list{
			get;  set;
		}

		/// <summary>
		/// 返回参数列表
		/// </summary>
		public IList<ApiParameter> response_parameter_list{
			get;  set;
		}

	}//end Api

}//end namespace Api