///////////////////////////////////////////////////////////
//  Api.cs
//  Implementation of the Class Api
//  Generated by Enterprise Architect
//  Created on:      20-9ÔÂ-2018 10:18:35
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder.Api;
namespace FD.Tiny.FormBuilder.Api {
	public class Api {

		public int api_id{
			get;  set;
		}

		public string api_name{
			get;  set;
		}

		public string api_desc{
			get;  set;
		}

		public string api_url{
			get;  set;
		}

		public string sql_content{
			get;  set;
		}

		public IList<ApiParameter> request_parameter_list{
			get;  set;
		}

		public IList<ApiParameter> response_parameter_list{
			get;  set;
		}

	}//end Api

}//end namespace Api