///////////////////////////////////////////////////////////
//  ApiData.cs
//  Implementation of the Class ApiData
//  Generated by Enterprise Architect
//  Created on:      18-10ÔÂ-2018 17:01:02
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public class ApiData {

		public string parameter_name{
			get;
			set;
		}

		public string value{
			get;
			set;
		}

	}//end ApiData

}//end namespace FD.Tiny.FormBuilder