///////////////////////////////////////////////////////////
//  ApiParameter.cs
//  Implementation of the Class ApiParameter
//  Generated by Enterprise Architect
//  Created on:      18-10月-2018 16:59:34
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 接口参数
	/// </summary>
	public class ApiParameter {

		/// <summary>
		/// 参数名称
		/// </summary>
		public string parameter_name{
			get;  set;
		}

		/// <summary>
		/// 参数中文名称
		/// </summary>
		public string parameter_name_chs{
			get;  set;
		}

		/// <summary>
		/// 备注
		/// </summary>
		public string remark{
			get;  set;
		}

		/// <summary>
		/// 数据类型
		/// </summary>
		public DataType data_type{
			get;  set;
		}

		/// <summary>
		/// 是否必填
		/// </summary>
		public bool is_required{
			get;  set;
		}

	}//end ApiParameter

}//end namespace FD.Tiny.FormBuilder