///////////////////////////////////////////////////////////
//  Condition.cs
//  Implementation of the Class Condition
//  Generated by Enterprise Architect
//  Created on:      22-10月-2018 16:12:33
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;



using FD.Tiny.FormBuilder;
using System.Text.RegularExpressions;
using FD.Tiny.Common.Utility.Calc;

namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 条件类
	/// </summary>
	public class Condition {
        
        /// <summary>
        /// 条件表达式
        /// </summary>
        public string condition_expr{
			get;
					set;
		}

		public ConditionItem condition_item{
			get;
			set;
		}
                        
    }//end Condition

}//end namespace FD.Tiny.FormBuilder