///////////////////////////////////////////////////////////
//  ConditionConfig.cs
//  Implementation of the Class ConditionConfig
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 14:20:53
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 条件配置
	/// </summary>
	public class ConditionConfig {

		/// <summary>
		/// 条件列表
		/// </summary>
		public List<Condition> condition_list{
			get;  set;
		}

	}//end ConditionConfig

}//end namespace FD.Tiny.FormBuilder