///////////////////////////////////////////////////////////
//  Condition.cs
//  Implementation of the Class Condition
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 14:20:53
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 条件类
	/// </summary>
	public class Condition {

		/// <summary>
		/// 条件表达式
		/// </summary>
		public string ondition_expr{
			get;
					set;
		}

	}//end Condition

}//end namespace FD.Tiny.FormBuilder