///////////////////////////////////////////////////////////
//  ConditionItem.cs
//  Implementation of the Class ConditionItem
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 14:20:54
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class ConditionItem {

		/// <summary>
		/// 取值方式
		/// </summary>
		public ValueMethod value_method{
			get;  set;
		}

		/// <summary>
		/// 替换值
		/// </summary>
		public string inner_value{
			get;  set;
		}

		/// <summary>
		/// 数据源配置
		/// </summary>
		public DataSource data_source_config{
			get;  set;
		}

		/// <summary>
		/// 数据库配置
		/// </summary>
		public FD.Tiny.FormBuilder.Database.DatabaseConfig data_base_config{
			get;  set;
		}

	}//end ConditionItem

}//end namespace FD.Tiny.FormBuilder