///////////////////////////////////////////////////////////
//  ConditionItem.cs
//  Implementation of the Class ConditionItem
//  Generated by Enterprise Architect
//  Created on:      23-10月-2018 11:27:32
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public class ConditionItem {

		/// <summary>
		/// 取值方式
		/// </summary>
		public ValueMethod value_method{
			get;  set;
		}

		/// <summary>
		/// 替换值
		/// </summary>
		public string inner_value{
			get;  set;
		}

	}//end ConditionItem

}//end namespace FD.Tiny.FormBuilder