///////////////////////////////////////////////////////////
//  ReplaceCondition.cs
//  Implementation of the Class ReplaceCondition
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 14:20:54
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 替换条件类
	/// </summary>
	public class ReplaceCondition : Condition {

		/// <summary>
		/// 条件项
		/// </summary>
		public ConditionItem conditon_item{
			get;
			set;
		}

	}//end ReplaceCondition

}//end namespace FD.Tiny.FormBuilder