///////////////////////////////////////////////////////////
//  ConnectionConfig.cs
//  Implementation of the Class ConnectionConfig
//  Generated by Enterprise Architect
//  Created on:      06-6ÔÂ-2018 13:02:44
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.DataAccess {
	public class ConnectionConfig {

		public DBType DbType { get;  set;} 
		public  string ConnectionString{ get;  set;} 

		public ConnectionConfig(){

		}

	}//end ConnectionConfig

}//end namespace FD.Tiny.DataAccess