///////////////////////////////////////////////////////////
//  DbType.cs
//  Implementation of the Enumeration DbType
//  Generated by Enterprise Architect
//  Created on:      06-6ÔÂ-2018 13:02:35
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.DataAccess {
	public enum DBType : int {

		Oracle,
		SqlServer

	}//end DbType

}//end namespace FD.Tiny.DataAccess