///////////////////////////////////////////////////////////
//  ConditionVariable.cs
//  Implementation of the Class ConditionVariable
//  Generated by Enterprise Architect
//  Created on:      23-10ÔÂ-2018 15:44:44
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public class ConditionVariable : FormVariable {

		public List<Condition> condition_list{
			get;
			set;
		}

        public override string GetValue(Func<string, string> getVal)
        {
            foreach (var condition in condition_list)
            {
                if (condition.ExecuteExpression(getVal))
                {
                    if (condition.condition_item.value_method == ValueMethod.Const)
                    {
                        return condition.condition_item.inner_value;
                    }
                    else
                    {
                        return getVal(condition.condition_item.inner_value);
                    }
                }
            }
            return string.Empty;
        }

    }//end ConditionVariable

}//end namespace Variable