///////////////////////////////////////////////////////////
//  LabelVariable.cs
//  Implementation of the Class LabelVariable
//  Generated by Enterprise Architect
//  Created on:      23-10ÔÂ-2018 9:05:48
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
using FD.Tiny.Common.Utility.Calc;
using System.Text.RegularExpressions;

namespace FD.Tiny.FormBuilder {
	public class LabelVariable : FormVariable {

        public LabelVariable()
        {
            this.variable_type = VariableType.Label;
        }

		public ValueMethod value_method{
			get;
			set;
		}
	        

        public override string GetValue(Func<string, string> val)
        {
            if (value_method == ValueMethod.Const)
            {
                return inner_value;
            }
            else
            {                
                return CalcExpression(val);
            }
            
        }

    }//end LabelVariable

}//end namespace Variable