///////////////////////////////////////////////////////////
//  LabelVariable.cs
//  Implementation of the Class LabelVariable
//  Generated by Enterprise Architect
//  Created on:      23-10ÔÂ-2018 9:05:48
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
using FD.Tiny.Common.Utility.Calc;

namespace FD.Tiny.FormBuilder {
	public class LabelVariable : FormVariable {

		public ValueMethod value_method{
			get;
			set;
		}

		public string inner_value{
			get;
			set;
		}

        public override string GetValue(Func<string, string> getVal)
        {
            if (value_method== ValueMethod.Const)
            {
                return inner_value;
            }
            else
            {
                return getVal(inner_value);
            }
            
        }

    }//end LabelVariable

}//end namespace Variable