///////////////////////////////////////////////////////////
//  BaseControl.cs
//  Implementation of the Class BaseControl
//  Generated by Enterprise Architect
//  Created on:      22-4月-2019 15:49:54
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public abstract class BaseControl {

		public BaseControl(){

		}

        /// <summary>
        /// 名称
        /// </summary>
		public string name{
			get;  set;
		}

        /// <summary>
        /// 值
        /// </summary>
		public string value{
			get;  set;
		}

        /// <summary>
        /// 控件类型
        /// </summary>
		public ControlType control_type{
			get; protected set;
		}

		/// <summary>
		/// 是否只读
		/// </summary>
		public bool? @readonly
        {
            get;
            set;
        }

		/// <summary>
		/// 提示文本
		/// </summary>
		public string placeholder{
			get;
			set;
		}

		/// <summary>
		/// 是否可清除
		/// </summary>
		public bool? clearable{
			get;
			set;
		}

        /// <summary>
        /// 是否有边框
        /// </summary>
		public bool? border{
			get;
			set;
		}

	}//end BaseControl

}//end namespace FD.Tiny.FormBuilder