///////////////////////////////////////////////////////////
//  CheckBox.cs
//  Implementation of the Class CheckBox
//  Generated by Enterprise Architect
//  Created on:      22-4ÔÂ-2019 15:49:57
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class CheckBox : BaseControl {
        public CheckBox()
        {
            this.control_type = ControlType.checkbox;
            this.@readonly = false;
            this.border = false;
        }

       
	}//end CheckBox

}//end namespace FD.Tiny.FormBuilder