///////////////////////////////////////////////////////////
//  Date.cs
//  Implementation of the Class Date
//  Generated by Enterprise Architect
//  Created on:      22-4月-2019 15:50:00
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 日期选择框
	/// </summary>
	public class Date : BaseControl {
        public Date()
        {
            this.control_type = ControlType.date;
            this.clearable = true;
            this.@readonly = false;
        }

	}//end Date

}//end namespace FD.Tiny.FormBuilder