///////////////////////////////////////////////////////////
//  Option.cs
//  Implementation of the Class Option
//  Generated by Enterprise Architect
//  Created on:      16-1月-2019 17:29:07
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public class Option {

		/// <summary>
		/// 选项key
		/// </summary>
		public string key{
			get;
						set;
		}

		/// <summary>
		/// 选项值
		/// </summary>
		public dynamic value{
			get;
						set;
		}

	}//end Option

}//end namespace FD.Tiny.FormBuilder