///////////////////////////////////////////////////////////
//  Radio.cs
//  Implementation of the Class Radio
//  Generated by Enterprise Architect
//  Created on:      22-4ÔÂ-2019 15:50:07
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class Radio : BaseControl {

        public Radio()
        {
            this.control_type = ControlType.radio;
            this.@readonly = false;
            this.border = false;
        }

	}//end Radio

}//end namespace FD.Tiny.FormBuilder