///////////////////////////////////////////////////////////
//  Select.cs
//  Implementation of the Class Select
//  Generated by Enterprise Architect
//  Created on:      22-4ÔÂ-2019 16:12:50
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class Select : BaseControl {

		public Select(){            
			this.control_type = ControlType.select;
            this.clearable = true;
            this.@readonly = false;            
		}

        /// <summary>
        /// ÊÇ·ñ¿ÉËÑË÷
        /// </summary>
        public bool filterable
        {
            get;
            set;
        } = true;

	}//end Select

}//end namespace FD.Tiny.FormBuilder