///////////////////////////////////////////////////////////
//  Slider.cs
//  Implementation of the Class Slider
//  Generated by Enterprise Architect
//  Created on:      22-4月-2019 15:50:13
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class Slider : BaseControl {

		public Slider(){

			this.control_type = ControlType.slider;
		}

        /// <summary>
        /// 最小值
        /// </summary>
		public int min{
			get; set;
		} = 0;

        /// <summary>
        /// 最大值
        /// </summary>
		public int max{
			get; set;
		} = 100;

        /// <summary>
        /// 步长
        /// </summary>
		public int step{
			get; set;
		} = 1;

        /// <summary>
        /// 格式化
        /// </summary>
		public string format_tooltip{
			get;
			set;
		}

        /// <summary>
        /// 是否显示断点
        /// </summary>
        public bool show_stops
        {
            get; set;
        } = true;

        /// <summary>
        /// 是否显示提示
        /// </summary>
		public bool show_tooltip{
			get; set;
		} = true;

	}//end Slider

}//end namespace FD.Tiny.FormBuilder