///////////////////////////////////////////////////////////
//  Switch.cs
//  Implementation of the Class Switch
//  Generated by Enterprise Architect
//  Created on:      22-4月-2019 15:50:15
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class Switch : BaseControl {

		public Switch(){

			this.control_type = ControlType.@switch;
            this.@readonly = false;
		}
       
        /// <summary>
        /// 打开文字
        /// </summary>
		public string active_text{
			get; set;
		}

        /// <summary>
        /// 关闭文字
        /// </summary>
		public string inactive_text{
			get; set;
		}

	}//end Switch

}//end namespace FD.Tiny.FormBuilder