///////////////////////////////////////////////////////////
//  Time.cs
//  Implementation of the Class Time
//  Generated by Enterprise Architect
//  Created on:      22-4ÔÂ-2019 15:50:18
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class Time : BaseControl {

        public Time()
        {
            this.control_type = ControlType.time;
            this.@readonly = false;
        }

	}//end Time

}//end namespace FD.Tiny.FormBuilder