///////////////////////////////////////////////////////////
//  FormStore.cs
//  Implementation of the Class FormStore
//  Generated by Enterprise Architect
//  Created on:      25-12月-2018 11:01:54
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 表单存储类
	/// </summary>
	public class FormStore {

		/// <summary>
		/// 存储ID
		/// </summary>
		public int store_id{
			get;  set;
		}

		/// <summary>
		/// 表单Id
		/// </summary>
		public int form_id{
			get;  set;
		}

		/// <summary>
		/// 标签数据列表
		/// </summary>
		public IList<LabelData> label_data_list{
			get;  set;
		}

		public int customer_id{
			get;
			set;
		}

	}//end FormStore

}//end namespace FD.Tiny.FormBuilder