///////////////////////////////////////////////////////////
//  FormStore.cs
//  Implementation of the Class FormStore
//  Generated by Enterprise Architect
//  Created on:      20-9ÔÂ-2018 10:38:26
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class FormStore {

		public int store_id{ get;  set;} 
		public int form_id{ get;  set;} 
		public IList<LabelData> label_data_list{ get;  set;} 
		public IList<FormData> form_data_list{ get;  set;} 
		public int customer_id{ get;  set;} 

	}//end FormStore

}//end namespace FD.Tiny.FormBuilder