///////////////////////////////////////////////////////////
//  FormData.cs
//  Implementation of the Class FormData
//  Generated by Enterprise Architect
//  Created on:      22-10月-2018 16:04:26
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 表单数据
	/// </summary>
	public class FormData {

		/// <summary>
		/// 变量Id
		/// </summary>
		public int variable_id{
			get;  set;
		}

		/// <summary>
		/// 变量值
		/// </summary>
		public dynamic variable_value{
			get;  set;
		}

		//public FormVariable form_variable{
		//	get;
		//	set;
		//}

		public string variable_name_chs{
			get;
			set;
		}

	}//end FormData

}//end namespace FD.Tiny.FormBuilder