///////////////////////////////////////////////////////////
//  DbTable.cs
//  Implementation of the Class DbTable
//  Generated by Enterprise Architect
//  Created on:      16-4ÔÂ-2019 19:19:02
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.ProjectBuilder {
	public class DbTable {

        public DbTable() { }
		/// 
		/// <param name="name"></param>
		public DbTable(string name){

			this.name = name;
		}

		/// <summary>
		/// Ãû³Æ
		/// </summary>
		public string name{
			get;  set;
		}

		/// <summary>
		/// ±¸×¢
		/// </summary>
		public string comment{
			get;  set;
		}

		public List<DbColumn> columns{
			get;  set;
		}

	}//end DbTable

}//end namespace FD.Tiny.ProjectBuilder