///////////////////////////////////////////////////////////
//  Dict.cs
//  Implementation of the Class Dict
//  Generated by Enterprise Architect
//  Created on:      21-11月-2018 11:15:21
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public class Dict {

		/// <summary>
		/// 字典类型Id
		/// </summary>
		public decimal dic_type_id{
			get; set;
		}

		/// <summary>
		/// 字典值
		/// </summary>
		public decimal dic_par_id{
			get; set;
		}

		/// <summary>
		/// 字典名称
		/// </summary>
		public string dic_par_name{
			get; set;
		}

		/// <summary>
		/// 排序
		/// </summary>
		public int order_no{
			get; set;
		}

	}//end Dict

}//end namespace Dict