///////////////////////////////////////////////////////////
//  FormVariable.cs
//  Implementation of the Class FormVariable
//  Generated by Enterprise Architect
//  Created on:      22-10月-2018 9:08:35
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class FormVariable {

		/// <summary>
		/// 变量Id
		/// </summary>
		public int variable_id{
			get;  set;
		}

		/// <summary>
		/// 表单Id
		/// </summary>
		public int form_id{
			get;  set;
		}

		/// <summary>
		/// 变量名称
		/// </summary>
		public string variable_name{
			get;  set;
		}

		/// <summary>
		/// 变量中文名
		/// </summary>
		public string variable_name_chs{
			get;  set;
		}

		/// <summary>
		/// 变量配置
		/// </summary>
		public ConditionConfig condition_config{
			get;  set;
		}

		/// <summary>
		/// 默认值
		/// </summary>
		public dynamic default_value{
			get;  set;
		}

		/// <summary>
		/// 数据类型
		/// </summary>
		public DataType data_type{
			get;  set;
		}

		/// <summary>
		/// 是否参数
		/// </summary>
		public bool is_parameter{
			get;  set;
		}

		/// <summary>
		/// 数据配置
		/// </summary>
		public DatabaseConfig database_config{
			get;  set;
		}

	}//end FormVariable

}//end namespace FD.Tiny.FormBuilder