///////////////////////////////////////////////////////////
//  FormType.cs
//  Implementation of the Class Category
//  Generated by Enterprise Architect
//  Created on:      20-9ÔÂ-2018 10:13:53
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public class Category {

		public int category_id{ get;  set;} 
		public string category_name{ get;  set;} 
		public int customer_id{ get;  set;} 
		public string category_desc{ get;  set;} 

	}//end Category

}//end namespace FD.Tiny.FormBuilder