///////////////////////////////////////////////////////////
//  Form.cs
//  Implementation of the Class Form
//  Generated by Enterprise Architect
//  Created on:      30-9月-2018 8:45:47
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;


using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 表单类
	/// </summary>
	public class Form {

        public Form()
        {
            this.variable_label_list = new List<Label>();
            this.form_params = new Dictionary<string, string>();
        }

        /// <summary>
        /// 初始化参数
        /// </summary>
        public Dictionary<string,string> form_params { get; set; }

		/// <summary>
		/// 表单Id
		/// </summary>
		public int form_id{
			get;  set;
		}

		/// <summary>
		/// 表单名称
		/// </summary>
		public string form_name{
			get;  set;
		}

		/// <summary>
		/// 表单描述
		/// </summary>
		public string form_desc{
			get;  set;
		}

		/// <summary>
		/// 分组列表
		/// </summary>
		public List<FormGroup> group_list{
			get;  set;
		}

        /// <summary>
        /// 变量标签
        /// </summary>
        public List<Label> variable_label_list { get; set; }

        /// <summary>
        /// 添加标签
        /// </summary>
        /// <param name="label"></param>
        public void AddLabel(Label label)
        {
            if (label is ControlLabel cLabel)
            {             
                var group = group_list.FirstOrDefault(g => g.group_name.Equals(cLabel.label_config.group_name));
                group.label_list.Add(cLabel);
            }
            else if(label is VariableLabel vLabel)
            {
                //初始化变量
                if (vLabel.label_config.is_parameter && form_params.ContainsKey(vLabel.label_name_chs))
                {
                    vLabel.inner_value = form_params[vLabel.label_name_chs];
                }
                variable_label_list.Add(label);
            }
            
        }      

	}//end Form

}//end namespace FD.Tiny.FormBuilder