///////////////////////////////////////////////////////////
//  BaseValidator.cs
//  Implementation of the Class BaseValidator
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 14:14:17
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 基础验证类
	/// </summary>
	public abstract class BaseValidator {

		/// <summary>
		/// 验证名称
		/// </summary>
		public string name{
			get;  set;
		}

		/// <summary>
		/// 提示信息
		/// </summary>
		public string show_msg{
			get;  set;
		}

		/// <summary>
		/// 焦点信息
		/// </summary>
		public string focus_msg{
			get;  set;
		}

		/// <summary>
		/// 错误信息
		/// </summary>
		public string error_msg{
			get;  set;
		}

		/// <summary>
		/// 是否可空
		/// </summary>
		public bool is_nullable{
			get;  set;
		}

		/// <summary>
		/// 数据类型
		/// </summary>
		public DataType data_type{
			get;  set;
		}

		/// <summary>
		/// 验证类型
		/// </summary>
		public ValidatorType validator_type{
			get;  set;
		}

	}//end BaseValidator

}//end namespace FD.Tiny.FormBuilder