///////////////////////////////////////////////////////////
//  InputValidator.cs
//  Implementation of the Class InputValidator
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 14:14:17
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 输入验证
	/// </summary>
	public class InputValidator : BaseValidator {

		/// <summary>
		/// 最大值
		/// </summary>
		public int min{
			get;  set;
		}

		/// <summary>
		/// 最小值
		/// </summary>
		public int max{
			get;  set;
		}

	}//end InputValidator

}//end namespace FD.Tiny.FormBuilder