///////////////////////////////////////////////////////////
//  RemoteValiator.cs
//  Implementation of the Class RemoteValiator
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 14:14:18
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 远程验证
	/// </summary>
	public class RemoteValiator : BaseValidator {

		/// <summary>
		/// 接口配置
		/// </summary>
		public DataSource data_source_config{
			get;  set;
		}

	}//end RemoteValiator

}//end namespace FD.Tiny.FormBuilder