///////////////////////////////////////////////////////////
//  ValidatorConfig.cs
//  Implementation of the Class ValidatorConfig
//  Generated by Enterprise Architect
//  Created on:      20-9ÔÂ-2018 14:14:19
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class ValidatorConfig {

		public List<BaseValidator> validator_list{
			get;  set;
		}

	}//end ValidatorConfig

}//end namespace FD.Tiny.FormBuilder