///////////////////////////////////////////////////////////
//  ApiDataSource.cs
//  Implementation of the Class ApiDataSource
//  Generated by Enterprise Architect
//  Created on:      13-4月-2019 15:32:24
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System.Collections.Generic;
using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 接口数据源
	/// </summary>
	public class ApiDataSource : DataSource {

		public ApiDataSource(){

			this.data_source_type = DataSourceType.DataApi;
		}

		/// <summary>
		/// 接口名称
		/// </summary>
		public string api_name{
			get;  set;
		}

		public int api_id{
			get;
						set;
		}

		/// <summary>
		/// 请求参数列表
		/// </summary>
		public Dictionary<string,string> request_parameter_map{
			get;  set;
		}

		/// <summary>
		/// 返回参数列表
		/// </summary>
		public Dictionary<string,string> response_parameter_map{
			get;
			set;
		}

	}//end ApiDataSource

}//end namespace FD.Tiny.FormBuilder