///////////////////////////////////////////////////////////
//  ApiDataSource.cs
//  Implementation of the Class ApiDataSource
//  Generated by Enterprise Architect
//  Created on:      25-9月-2018 16:18:09
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using FD.Tiny.FormBuilder;

namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 接口数据源
	/// </summary>
	public class ApiDataSource : DataSource {

		/// <summary>
		/// 接口名称
		/// </summary>
		public string api_name{
			get;  set;
		}

		/// <summary>
		/// 参数列表
		/// </summary>
		public Dictionary<string,string> parameter_list{
			get;  set;
		}

	}//end ApiDataSource

}//end namespace FD.Tiny.FormBuilder