///////////////////////////////////////////////////////////
//  CustomDataSource.cs
//  Implementation of the Class CustomDataSource
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:36:53
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 自定义数据源
	/// </summary>
	public class CustomDataSource : DataSource {

		/// <summary>
		/// 分割符
		/// </summary>
		public int separtor{
			get;  set;
		}

		/// <summary>
		/// 数据值
		/// </summary>
		public string value{
			get;  set;
		}

	}//end CustomDataSource

}//end namespace FD.Tiny.FormBuilder