///////////////////////////////////////////////////////////
//  CustomDataSource.cs
//  Implementation of the Class CustomDataSource
//  Generated by Enterprise Architect
//  Created on:      25-9月-2018 16:18:10
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 自定义数据源
	/// </summary>
	public class CustomDataSource : DataSource {


        public CustomDataSource()
        {
            this.data_source_type = DataSourceType.Custom;
        }

		/// <summary>
		/// 分割符
		/// </summary>
		public string separtor{
			get;  set;
		}

		/// <summary>
		/// 数据值
		/// </summary>
		public string value{
			get;  set;
		}

	}//end CustomDataSource

}//end namespace FD.Tiny.FormBuilder