///////////////////////////////////////////////////////////
//  DataSource.cs
//  Implementation of the Class DataSource
//  Generated by Enterprise Architect
//  Created on:      25-9月-2018 16:18:12
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 数据源类
	/// </summary>
	public  class DataSource {

		/// <summary>
		/// 数据源类型
		/// </summary>
		public DataSourceType data_source_type{
			get;  set;
		}

	}//end DataSource

}//end namespace FD.Tiny.FormBuilder