///////////////////////////////////////////////////////////
//  DictSource.cs
//  Implementation of the Class DictSource
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:36:54
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 字典数据源
	/// </summary>
	public class DictSource : DataSource {

		/// <summary>
		/// 字典类型
		/// </summary>
		public int dic_type_id{
			get;  set;
		}

		/// <summary>
		/// 字典子类型值
		/// </summary>
		public string dic_par_ids{
			get;  set;
		}

	}//end DictSource

}//end namespace FD.Tiny.FormBuilder