///////////////////////////////////////////////////////////
//  BaseFormat.cs
//  Implementation of the Class BaseFormat
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:25:03
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 格式化基类
	/// </summary>
	public abstract class BaseFormat {

		/// <summary>
		/// 格式化字符串
		/// </summary>
		public string format_str{
			get;  set;
		}

		/// <summary>
		/// 格式化类型
		/// </summary>
		public FormatType format_type{
			get;  set;
		}

		/// <summary>
		/// 格式化值
		/// </summary>
		public dynamic value{
			get;  set;
		}

		/// <summary>
		/// 格式化结果
		/// </summary>
		public string result{
			get;  set;
		}

	}//end BaseFormat

}//end namespace FD.Tiny.FormBuilder