///////////////////////////////////////////////////////////
//  DataSourceFormat.cs
//  Implementation of the Class DataSourceFormat
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:25:03
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 数据源格式化
	/// </summary>
	public class DataSourceFormat : BaseFormat {

		/// <summary>
		/// 数据源配置
		/// </summary>
		public DataSource data_source_config{
			get;  set;
		}

	}//end DataSourceFormat

}//end namespace FD.Tiny.FormBuilder