///////////////////////////////////////////////////////////
//  DateFormat.cs
//  Implementation of the Class DateFormat
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:25:03
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 室间格式化类
	/// </summary>
	public class DateFormat : BaseFormat {

		/// <summary>
		/// 是否格式化中文时间
		/// </summary>
		public bool is_chinese_date{
			get;  set;
		}

	}//end DateFormat

}//end namespace FD.Tiny.FormBuilder