///////////////////////////////////////////////////////////
//  NumerFormat.cs
//  Implementation of the Class NumerFormat
//  Generated by Enterprise Architect
//  Created on:      20-9月-2018 10:25:03
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 数字格式化
	/// </summary>
	public class NumerFormat : BaseFormat {

		/// <summary>
		/// 精度
		/// </summary>
		public int precision{
			get;  set;
		}

		/// <summary>
		/// 长度
		/// </summary>
		public int length{
			get;  set;
		}

		/// <summary>
		/// 除数
		/// </summary>
		public double divide_by{
			get;  set;
		}

		/// <summary>
		/// 是否千分位
		/// </summary>
		public bool is_thousands{
			get;  set;
		}

		/// <summary>
		/// 格式化模式
		/// </summary>
		public FormatNumberMode number_mode{
			get;  set;
		}

	}//end NumerFormat

}//end namespace FD.Tiny.FormBuilder