///////////////////////////////////////////////////////////
//  DataSourceController.cs
//  Implementation of the Class DataSourceController
//  Generated by Enterprise Architect
//  Created on:      15-10ÔÂ-2018 10:40:50
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System.Web.Mvc;
namespace FD.Tiny.FormBuilder.Demo.Controllers {
	public class DataSourceController : Controller {

		/// <summary>
		/// GET: DataSource
		/// </summary>
		public ActionResult Index(){

			return View();
		}

		/// <summary>
		/// GET: DataSource
		/// </summary>
		public ActionResult Add(){

			return View();
		}

		/// <summary>
		/// GET: DataSource
		/// </summary>
		public ActionResult Save(){

			return View();
		}

		/// <summary>
		/// GET: DataSource
		/// </summary>
		public ActionResult Del(){

			return View();
		}

		/// <summary>
		/// GET: DataSource
		/// </summary>
		public ActionResult Search(){

			return View();
		}

	}//end DataSourceController

}//end namespace Controllers