///////////////////////////////////////////////////////////
//  DataBaseController.cs
//  Implementation of the Class DataBaseController
//  Generated by Enterprise Architect
//  Created on:      15-10ÔÂ-2018 15:42:37
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
using FD.Tiny.Common.Utility.PageHeler;
using System.Web.Http;

namespace FD.Tiny.FormBuilder.Demo.Controllers {
	public class DataBaseController : ApiController {

		private FD.Tiny.FormBuilder.DbTableService _dbTableService;
		private FD.Tiny.FormBuilder.DbColumnService _dbColumnService;

		/// 
		/// <param name="dbTableService"></param>
		/// <param name="dbColumnService"></param>
		public DataBaseController(DbTableService dbTableService, DbColumnService dbColumnService){

			_dbTableService = dbTableService;
			_dbColumnService = dbColumnService;
		}

		/// 
		/// <param name="schemal"></param>
		public IHttpActionResult Index(string schemal){

			var list = _dbTableService.QueryDbTable(schemal);
			return Json(new OkResponse(list));
		}

        /// <summary>
        /// GET: DataBase
        /// </summary>
        /// <param name="table"></param>
        [HttpPost]
        public IHttpActionResult AddTable(DbTable table){
            var result = _dbTableService.AddDbTable(table, 0);
			return Json(new OkResponse(result));
		}

        /// <summary>
        /// GET: DataBase
        /// </summary>
        /// <param name="table"></param>
        [HttpPost]
        public IHttpActionResult UpdateTable(DbTable table){
            _dbTableService.SaveDbTable(table, 0);
			return Json(new OkResponse());
		}

        /// <summary>
        /// GET: DataBase
        /// </summary>
        /// <param name="tableId"></param>
        [HttpPost]
        public IHttpActionResult DelTable(int tableId)
        {
            _dbTableService.DelDbTable(tableId, 0);
            return Json(new OkResponse());
        }

        /// <summary>
        /// GET: DataBase
        /// </summary>
        /// <param name="column"></param>
        [HttpPost]
        public IHttpActionResult AddColumn(DbColumn column)
        {
            var result =  _dbColumnService.AddDbColumn(column, 0);
            return Json(new OkResponse(result));
        }

        /// <summary>
        /// GET: DataBase
        /// </summary>
        /// <param name="column"></param>
        [HttpPost]
        public IHttpActionResult UpdateColumn(DbColumn column){
            _dbColumnService.SaveDbColumn(column, 0);
            return Json(new OkResponse());
        }

        /// <summary>
        /// GET: DataBase
        /// </summary>
        /// <param name="columnId"></param>
        [HttpPost]
        public IHttpActionResult DelColumn(int columnId)
        {
            _dbColumnService.DelDbColumn(columnId, 0);
            return Json(new OkResponse());
        }

	}//end DataBaseController

}//end namespace Controllers