///////////////////////////////////////////////////////////
//  DataApiController.cs
//  Implementation of the Class DataApiController
//  Generated by Enterprise Architect
//  Created on:      17-10ÔÂ-2018 9:00:12
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System.Web.Mvc;
using FD.Tiny.Common.Utility.PageHeler;

namespace FD.Tiny.FormBuilder.Demo.Controllers {
	public class DataApiController : Controller {

        private ApiService _apiService;

        public DataApiController(ApiService apiService)
        {
            _apiService = apiService;
        }

        /// <summary>
        /// GET: DataSource
        /// </summary>
        public ActionResult Index(string name)
        {
            var list = _apiService.QueryApi(name);
            return Json(new OkResponse(list), JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult ParseSql(string sql)
        {
            var parsedSql = _apiService.ParseSql(sql);
            var requestList = _apiService.GetRequestParamsFromSql(sql);
            var respList = _apiService.GetResponseParamsFromSql(sql);
            return Json(new OkResponse(new
            {
                parsedSql,
                requestList,
                respList,
            }));
        }

        /// <summary>
        /// GET: DataSource
        /// </summary>
        [HttpPost]
        public ActionResult Add(Api api)
        {
            var result = _apiService.AddApi(api, 0);
            return Json(new OkResponse(result));
        }

        /// <summary>
        /// GET: DataSource
        /// </summary>
        [HttpPost]
        public ActionResult Save(Api api){
            _apiService.SaveApi(api, 0);
			return Json(new OkResponse());
		}

        /// <summary>
        /// GET: DataSource
        /// </summary>
        [HttpPost]
        public ActionResult Del(int apiId){
            _apiService.DelApi(apiId, 0);
			return Json(new OkResponse());
		}
		 

	}//end DataApiController

}//end namespace Controllers