///////////////////////////////////////////////////////////
//  DataType.cs
//  Implementation of the Enumeration DataType
//  Generated by Enterprise Architect
//  Created on:      14-6ÔÂ-2018 10:35:33
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.DataBuilder {
	public enum OracleDataType : int {

		Number,
		Varchar2,
		NVarchar2,
		Date,
		Decimal,
		Integer

	}//end DataType

}//end namespace Data