///////////////////////////////////////////////////////////
//  OracleMaintenacneProvider.cs
//  Implementation of the Class OracleMaintenacneProvider
//  Generated by Enterprise Architect
//  Created on:      14-6ÔÂ-2018 10:35:34
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.DataBuilder;
namespace FD.Tiny.DataBuilder {
	public class OracleMaintenacneProvider : DbMaintenanceProvider {
        protected override string GetColumnInfosByTableNameSql
        {
            get
            {
                throw new NotSupportedException();
            }
        }
        protected override string GetTableInfoListSql
        {
            get
            {
                return @"SELECT  table_name name from user_tables where
                        table_name!='HELP' 
                        AND table_name NOT LIKE '%$%'
                        AND table_name NOT LIKE 'LOGMNRC_%'
                        AND table_name!='LOGMNRP_CTAS_PART_MAP'
                        AND table_name!='LOGMNR_LOGMNR_BUILDLOG'
                        AND table_name!='SQLPLUS_PRODUCT_PROFILE'  
                         ";
            }
        }

        public OracleMaintenacneProvider(){

		}

    
        protected override string AddColumnToTableSql
        {
            get { return "ALTER TABLE {0} ADD {1} {2}{3} {4} {5} {6}"; }
        }

        protected override string CreateTableSql
        {
            get { return "CREATE TABLE {0}(\r\n{1})"; }
        }


        protected override string AlterColumnToTableSql
        {
            get { return "ALTER TABLE {0} ALTER COLUMN {1} {2}{3} {4} {5} {6}"; }
        }

        protected override string CreateTableColumnSql
        {
            get { return "{0} {1}{2} {3} {4} {5}"; }
        }

        protected override string DropTableSql
        {
            get { return "DROP TABLE {0}"; }
        }

        protected override string DropColumnToTableSql
        {
            get { return "ALTER TABLE {0} DROP COLUMN {1}"; }
        }

        protected override string AddPrimaryKeySql
        {
            get { return "ALTER TABLE {0} ADD CONSTRAINT {1} PRIMARY KEY({2})"; }
        }

        protected override string CreateTableNull
        {
            get
            {
                return "NULL";
            }
        }

		protected override string CreateTableNotNull{
            get
            {
                return "NOT NULL";
            }
		}

		protected override string CreateTablePrimaryKey{
            get
            {
                return "PRIMARY KEY";
            }
		}

		protected override string CreateSequenceSql{
			get {
                return @"CREATE SEQUENCE {0} MINVALUE {1} MAXVALUE {2} START WITH {3} INCREMENT BY {4} CACHE {5} NOCYCLE; ";
            }
		}

     

        protected override string CreateTableIdentity{
            get
            {
                return "IDENTITY(1,1)";
            }
        }

		protected override string DropConstraintSql{
            get
            {
                return "ALTER TABLE {0} DROP CONSTRAINT  {1}";
            }
        }

       
        protected override string DropSequenceSql{
            get
            {
                return "DROP SEQUENCE {0}";
            }
        }

	}//end OracleMaintenacneProvider

}//end namespace OracleProvider