///////////////////////////////////////////////////////////
//  BaseSingleSqlParser .cs
//  Implementation of the Class BaseSingleSqlParser 
//  Generated by Enterprise Architect
//  Created on:      13-11ÔÂ-2018 16:08:30
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;

namespace FD.Tiny.FormBuilder {
    public abstract class BaseSingleSqlParser
    {

        protected string OriginalSql;
        protected List<SqlSegment> Segments;

        /// 
        /// <param name="originalSql"></param>
        public BaseSingleSqlParser(string originalSql)
        {
            this.OriginalSql = originalSql;
            Segments = new List<SqlSegment>();
            initializeSegments();
            SplitSqlToSegment();
            
        }

        protected void SplitSqlToSegment()
        {
            foreach (var sqlSegment in Segments)
            {
                sqlSegment.Parse(OriginalSql);                
            }
        }

        protected abstract void initializeSegments();

        public string GetParsedSql()
        {
            StringBuilder sb = new StringBuilder();
            foreach (var sqlSegment in Segments)
            {
                sb.Append(sqlSegment.GetParsedSqlSegment());
            }
            //var result = sb.ToString().Replace("$+", "\n");
            return sb.ToString();
        }

        public List<SqlSegment> ReturnSqlSegments()
        {
            var segmentLength = this.Segments.Count();
            if (segmentLength != 0)
            {
                var result = this.Segments;
                return result;
            }
            return null;
        }

    }

 
}//end namespace FD.Tiny.FormBuilder