///////////////////////////////////////////////////////////
//  SqlParserUtil.cs
//  Implementation of the Class SqlParserUtil
//  Generated by Enterprise Architect
//  Created on:      13-11ÔÂ-2018 15:12:50
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.FormBuilder {
	public class SqlParserUtil {

		/// 
		/// <param name="sql"></param>
		public string GetParsedSql(string sql){
            sql = sql.Trim().Replace("s+", "    ");
            sql = "" + sql + " ENDOFSQL";
			return SingleSqlParserFactory.GenerateParser(sql).GetParsedSql();
		}

		/// 
		/// <param name="sql"></param>
		public List<SqlSegment> GetParsedSqlSegmentList(string sql){
            sql = sql.Trim().Replace("s+", "    ");
            sql = "" + sql + " ENDOFSQL";
            return SingleSqlParserFactory.GenerateParser(sql).ReturnSqlSegments();
		}

	}//end SqlParserUtil

}//end namespace FD.Tiny.FormBuilder