///////////////////////////////////////////////////////////
//  Autocomplete.cs
//  Implementation of the Class Autocomplete
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:24
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class Autocomplete {

		public Autocomplete(){

		}

		public string url{
			get;
			set;
		}

		public IList<QueryParam> param_list{
			get;
			set;
		}

		public ResultFormatter response_formatter{
			get;
			set;
		}

	}//end Autocomplete

}//end namespace FD.Tiny.UI.Controls