///////////////////////////////////////////////////////////
//  BaseControl.cs
//  Implementation of the Class BaseControl
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:24
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.UI.Controls {
	public abstract class BaseControl {

		public BaseControl(){

		}

		public string name{
			get;  set;
		}

		public string value{
			get;  set;
		}

		public ControlType type{
			get; protected set;
		}

		public bool is_required{
			get;  set;
		}

		public bool disabled{
			get;
					set;
		}

	}//end BaseControl

}//end namespace FD.Tiny.UI.Controls