///////////////////////////////////////////////////////////
//  CheckBox.cs
//  Implementation of the Class CheckBox
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class CheckBox : BaseControl {

		public CheckBox(){

		}

		public bool is_checked{
			get;
			set;
		}

	}//end CheckBox

}//end namespace FD.Tiny.UI.Controls