///////////////////////////////////////////////////////////
//  DataSourceMode.cs
//  Implementation of the Enumeration DataSourceMode
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.UI.Controls {
	public enum DataSourceMode : int {

		remote,
		local

	}//end DataSourceMode

}//end namespace FD.Tiny.UI.Controls