///////////////////////////////////////////////////////////
//  DateControl.cs
//  Implementation of the Class DatePicker
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class DatePicker : BaseControl {

		public DatePicker(){

		}

		public DateTime max_date{
			get;  set;
		}

		public DateTime min_date{
			get;  set;
		}

		public bool editable{
			get;
			set;
		}

		public string formatter{
			get;
			set;
		}

		public DateMode mode{
			get;
			set;
		}

		public string rang_separator{
			get;
			set;
		}

	}//end DatePicker

}//end namespace FD.Tiny.UI.Controls