///////////////////////////////////////////////////////////
//  DateControl.cs
//  Implementation of the Class DatePicker
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class DatePicker : BaseControl {

		public DatePicker(){

		}

        public string placeholder { get; set; }

        public bool time_picker { get; set; }

        public DateMode type { get; set; }

        public bool @readonly { get; set; }

        public bool editable { get; set; }

        public bool clearable { get; set; }

        public SizeMode size { get; set; }

        public TimeSelect options { get; set; }

        public string start_placeholder { get; set; }

        public string end_placeholder { get; set; }

        public bool is_range { get; set; }

        public bool arrow_control { get; set; }

        public string range_separator { get; set; } = "-";

        public string value_format { get; set; }

        public string default_value { get; set; }
        

		public string format{
			get;
			set;
		}
		 

		public string rang_separator{
			get;
			set;
		}

	 

	}//end DatePicker

}//end namespace FD.Tiny.UI.Controls