///////////////////////////////////////////////////////////
//  InputNumber.cs
//  Implementation of the Class InputNumber
//  Generated by Enterprise Architect
//  Created on:      12-7ÔÂ-2018 14:46:32
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class InputNumber : BaseControl {

		public InputNumber(){
            this.control_type = ControlType.inputNumber;
		}

        public float min { get; set; }

        public float max { get; set; }

        public float step { get; set; }

        public int precision { get; set; }

        public SizeMode size { get; set; }

        public bool controls { get; set; }

        public string label { get; set; }





    }//end InputNumber

}//end namespace FD.Tiny.UI.Controls