///////////////////////////////////////////////////////////
//  QueryParam.cs
//  Implementation of the Class QueryParam
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.UI.Controls {
	public class QueryParam {

		/// <summary>
		/// Ãû³Æ
		/// </summary>
		public string name{ get;  set;} 
		/// <summary>
		/// Öµ
		/// </summary>
		public string value{ get;  set;} 

		public QueryParam(){

		}

	}//end QueryParam

}//end namespace FD.Tiny.UI.Controls