///////////////////////////////////////////////////////////
//  Radio.cs
//  Implementation of the Class Radio
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class Radio : BaseControl {

        public Radio()
        {
            this.control_type = ControlType.radio;
        }

		public string label
        {
            get { return value; }
            set { this.value = value; }
        }

		public bool is_checked{
			get;
			set;
		}

        public string text { get; set; }        

        public SizeMode size { get; set; }

    }//end Radio

}//end namespace FD.Tiny.UI.Controls