///////////////////////////////////////////////////////////
//  Radio.cs
//  Implementation of the Class Radio
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class Radio : BaseControl {

		public Radio(){

		}

	}//end Radio

}//end namespace FD.Tiny.UI.Controls