///////////////////////////////////////////////////////////
//  ResultFormatter.cs
//  Implementation of the Class ResultFormatter
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.UI.Controls {
	public class ResultFormatter {

		public ResultFormatter(){

		}

		public string label{
			get;
			set;
		}

		public string value{
			get;
			set;
		}

	}//end ResultFormatter

}//end namespace FD.Tiny.UI.Controls