///////////////////////////////////////////////////////////
//  SelectItem.cs
//  Implementation of the Class Option
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.UI.Controls {
	public class Option {

		public Option(){

		}

		/// 
		/// <param name="label"></param>
		/// <param name="value"></param>
		public Option(string label, string value){

			this.label = label;
			this.value = value;
		}

		public string label{
			get;  set;
		}

		public string value{
			get;  set;
		}

        public bool? disabled { get; set; }

        public Option[] options { get; set; }

    }//end Option

}//end namespace FD.Tiny.UI.Controls