///////////////////////////////////////////////////////////
//  SelectControl.cs
//  Implementation of the Class Select
//  Generated by Enterprise Architect
//  Created on:      29-4月-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class Select : BaseControl {

		public Select(){

		}

		public bool multiple{
			get;  set;
		}

		public List<Option> options{
			get;  set;
		}

		public string placeholder{
			get;
			set;
		}

		public bool remote{
			get;  set;
		}

		public List<string> relation_control_name{
			get;  set;
		}

		/// <summary>
		/// 多选限制数
		/// </summary>
		public int multiple_limit{
			get;
			set;
		}

		/// <summary>
		/// 是否可搜索
		/// </summary>
		public bool filterable{
			get;
			set;
		}

		public Autocomplete autocomplete{
			get;
			set;
		}

	}//end Select

}//end namespace FD.Tiny.UI.Controls