///////////////////////////////////////////////////////////
//  SelectControl.cs
//  Implementation of the Class Select
//  Generated by Enterprise Architect
//  Created on:      29-4月-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class Select : BaseControl {

		public Select(){
            this.control_type = ControlType.select;
		}

		public bool multiple{
			get;  set;
		}

		public List<Option> options{
			get;  set;
		}

        public bool clearable { get; set; } = false;

        public bool loading { get; set; } = false;

        public string no_match_text { get; set; }

        public string no_data_text { get; set; }

        public bool default_first_option { get; set; }

        public string loading_text { get; set; }

        public string placeholder{
			get;
			set;
		}

		public bool remote{
			get;  set;
		}

		public List<string> relation_control_name{
			get;  set;
		}

		/// <summary>
		/// 多选限制数
		/// </summary>
		public int multiple_limit{
			get;
			set;
		}

		/// <summary>
		/// 是否可搜索
		/// </summary>
		public bool filterable{
			get;
			set;
		}

		public Autocomplete autocomplete{
			get;
			set;
		}

	}//end Select

}//end namespace FD.Tiny.UI.Controls