///////////////////////////////////////////////////////////
//  SizeMode.cs
//  Implementation of the Enumeration SizeMode
//  Generated by Enterprise Architect
//  Created on:      11-7ÔÂ-2018 10:52:49
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.UI.Controls {
	public enum SizeMode : int {

		medium,
		small,
		mini

	}//end SizeMode

}//end namespace FD.Tiny.UI.Controls