///////////////////////////////////////////////////////////
//  Slider.cs
//  Implementation of the Class Slider
//  Generated by Enterprise Architect
//  Created on:      12-7ÔÂ-2018 16:26:13
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class Slider : BaseControl {

		public Slider(){
            this.control_type = ControlType.slider;
		}

        public int min { get; set; } = 0;

        public int max { get; set; } = 100;

        public int step { get; set; } = 1;

        public bool show_input { get; set; }

        public bool show_input_controls { get; set; } 

        public SizeMode input_size { get; set; }

        public bool show_stops { get; set; }

        public bool show_tooltip { get; set; } = true;

        public bool range { get; set; }

        public bool vertical { get; set; }

        public string height { get; set; }



    }//end Slider

}//end namespace FD.Tiny.UI.Controls