///////////////////////////////////////////////////////////
//  Switch.cs
//  Implementation of the Class Switch
//  Generated by Enterprise Architect
//  Created on:      12-7ÔÂ-2018 16:17:37
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class Switch : BaseControl {

		public Switch(){
            this.control_type = ControlType.@switch;
		}

        public string active_text { get; set; }

        public string inactive_text { get; set; }

        public string active_value { get; set; }

        public string inactive_value { get; set; }

        public bool is_checked { get; set; }

    }//end Switch

}//end namespace FD.Tiny.UI.Controls