///////////////////////////////////////////////////////////
//  TextControl.cs
//  Implementation of the Class Input
//  Generated by Enterprise Architect
//  Created on:      29-4ÔÂ-2018 11:57:25
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.UI.Controls;
namespace FD.Tiny.UI.Controls {
	public class Input : BaseControl {

		public Input(){

			this.type = ControlType.input;
		}

		public string placeholder{
			get;  set;
		}

		public int max_length{
			get;
					set;
		}

		public int min_length{
			get;
					set;
		}

		public string max{
			get;
					set;
		}

		public string min{
			get;
					set;
		}

		public Autocomplete autocomplete{
			get;
					set;
		}

		public InputMode mode{
			get;
			set;
		}

	}//end Input

}//end namespace FD.Tiny.UI.Controls