///////////////////////////////////////////////////////////
//  TimeSelect.cs
//  Implementation of the Class TimeSelect
//  Generated by Enterprise Architect
//  Created on:      12-7ÔÂ-2018 17:09:39
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace FD.Tiny.UI.Controls {
	public class TimeSelect {

        public string start { get; set; }

        public string end { get; set; }

        public string step { get; set; }

        public string minTime { get; set; }
        public string maxTime { get; set; }

        public string[] selectableRange { get; set; }

        public string format { get; set; }
    }//end TimeSelect

}//end namespace FD.Tiny.UI.Controls