///////////////////////////////////////////////////////////
//  ConditionConfig.cs
//  Implementation of the Class ConditionConfig
//  Generated by Enterprise Architect
//  Created on:      24-12‘¬-2018 16:58:34
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// Ãıº˛≈‰÷√
	/// </summary>
	public class ConditionConfig : LabelConfig {

		public List<Condition> condition_list{
			get;
						set;
		}

	}//end ConditionConfig

}//end namespace FD.Tiny.FormBuilder