///////////////////////////////////////////////////////////
//  ControlConfig.cs
//  Implementation of the Class ControlConfig
//  Generated by Enterprise Architect
//  Created on:      24-12ÔÂ-2018 16:58:36
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// ¿Ø¼þÅäÖÃ
	/// </summary>
	public class ControlConfig : LabelConfig {

        public List<Option> control_options
        {
            get;
            set;
        } 

        public ValidatorConfig validator_config
        {
            get;
            set;
        } 

		public int label_sort{
			get;
			set;
		}

		public string control_type{
			get;
			set;
		}

		public string group_name{
			get;
			set;
		}

	}//end ControlConfig

}//end namespace FD.Tiny.FormBuilder