///////////////////////////////////////////////////////////
//  ControlLabel.cs
//  Implementation of the Class ControlLabel
//  Generated by Enterprise Architect
//  Created on:      24-12ÔÂ-2018 17:01:18
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// ¿Ø¼þ±êÇ©
	/// </summary>
	public class ControlLabel : Label {

		public ControlLabel(){

			this.label_type = LabelType.control;
		}

		public new ControlConfig label_config{
			get;
						set;
		}

        public override string GetValue(Func<string, string> source)
        {
            return source(label_name_chs);
        }

    }//end ControlLabel

}//end namespace FD.Tiny.FormBuilder