///////////////////////////////////////////////////////////
//  LabelConfig.cs
//  Implementation of the Class LabelConfig
//  Generated by Enterprise Architect
//  Created on:      24-12月-2018 16:58:44
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 表单变量
	/// </summary>
	public class LabelConfig {

		/// <summary>
		/// 数据源配置
		/// </summary>
		public DataSource data_source_config{
			get;  set;
		}

		/// <summary>
		/// 关联配置
		/// </summary>
		public RelateConfig relate_config{
			get;  set;
		}

		/// <summary>
		/// 数据库配置
		/// </summary>
		public DatabaseConfig database_config{
			get;
			set;
		}

		/// <summary>
		/// 格式化配置
		/// </summary>
		public BaseFormat format_config{
			get;  set;
		}

		/// <summary>
		/// 地图配置
		/// </summary>
		public Map map_config{
			get;
			set;
		}

	}//end LabelConfig

}//end namespace FD.Tiny.FormBuilder