///////////////////////////////////////////////////////////
//  LabelConfig.cs
//  Implementation of the Class LabelConfig
//  Generated by Enterprise Architect
//  Created on:      28-9月-2018 16:52:32
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	/// <summary>
	/// 表单变量
	/// </summary>
	public class LabelConfig {

		/// <summary>
		/// 验证配置
		/// </summary>
		public ValidatorConfig validator_config{
			get;  set;
		}

		/// <summary>
		/// 条件配置
		/// </summary>
		public ConditionConfig condition_config{
			get;  set;
		}

		/// <summary>
		/// 数据源配置
		/// </summary>
		public DataSource data_source_config{
			get;  set;
		}

		/// <summary>
		/// 数据库配置
		/// </summary>
		public DatabaseConfig data_base_config{
			get;  set;
		}

		/// <summary>
		/// 关联配置
		/// </summary>
		public RelateConfig relate_config{
			get;  set;
		}

		/// <summary>
		/// 格式化配置
		/// </summary>
		public BaseFormat format_config{
			get;  set;
		}

		public Map map_config{
			get;
			set;
		}

	}//end LabelConfig

}//end namespace FD.Tiny.FormBuilder