///////////////////////////////////////////////////////////
//  VariableLabel.cs
//  Implementation of the Class VariableLabel
//  Generated by Enterprise Architect
//  Created on:      24-12ÔÂ-2018 17:30:10
//  Original author: drago
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using FD.Tiny.FormBuilder;
namespace FD.Tiny.FormBuilder {
	public class VariableLabel : Label {

		public VariableLabel(){

			this.label_type = LabelType.variable;
		}

		public new VariableConfig label_config{
			get;
			set;
		}

		/// 
		/// <param name="val"></param>
		public override string GetValue(Func<string, string> source){
            if(label_config.value_method == ValueMethod.Const)
            {
                return this.inner_value;
            }
            else
            {
                return CalcExpression(source);
            }
		
		}

	}//end VariableLabel

}//end namespace FD.Tiny.FormBuilder